"""domain_spec.py — CORTEX-PE v16.17
═══════════════════════════════════════════════════════════════════════════════
Domain specification and registry.

A DomainSpec fully describes a new domain to the CORTEX-PE system — enough
for the scaffold generator to build training + eval scripts, and for the
intervention executor to know how to improve them.

Adding a new domain:
  1. Create a DomainSpec (see examples at the bottom of this file)
  2. Register it: REGISTRY["my_domain"] = my_spec
  3. Run: python domain_scaffold.py --domain my_domain
  4. The system generates train_my_domain.py + eval_my_domain.py
  5. First run is committed to lineage automatically
  6. Subsequent improvements are driven by the intervention table

Modalities supported:
  "image"      — RGB frames, StudentEncoder backbone
  "audio"      — 1-D waveform or spectrogram, BEATs/wav2vec2 teacher
  "telemetry"  — multivariate time series, SubspaceAD head
  "tabular"    — structured feature vectors, PCA + anomaly scoring

Heads available per modality:
  image:     RoPETemporalHead, QuasimetricHead, SubspaceAD, ClassifierHead
  audio:     ProjectionHead, SubspaceAD, ClassifierHead
  telemetry: SubspaceAD, IsolationForest, ClassifierHead
  tabular:   SubspaceAD, IsolationForest
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any


# ─────────────────────────────────────────────────────────────────────────────
# Core spec
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class DomainSpec:
    """Complete specification of a CORTEX-PE domain.

    Parameters
    ----------
    name : str
        Short identifier used in filenames and lineage keys. e.g. "recon".
    description : str
        One-sentence description of the task.
    modality : str
        Input modality: "image", "audio", "telemetry", "tabular".
    data_path : str
        Path to the dataset root on the NUC. Relative to CORTEX dir.
    data_format : str
        File format: "hdf5", "wav", "csv", "npy", "folder_of_images".
    data_notes : str
        Key layout, gotchas, decode requirements.
        e.g. "images/rgb_left stores JPEG bytes as fixed-length HDF5 strings"
    primary_metric : str
        The metric that defines improvement. e.g. "auroc", "triplet_ordering".
    primary_metric_target : float
        Success threshold. Training stops recommending interventions above this.
    teacher : str | None
        Pre-trained teacher model, if any. e.g. "dinov2_small", "beats".
    head : str
        Head architecture for the downstream task.
        e.g. "RoPETemporalHead", "SubspaceAD", "ProjectionHead".
    loss : str
        Training objective. e.g. "triplet_infonce", "distillation", "subspace".
    eval_script : str
        Name of the evaluation script. Generated by scaffold if not existing.
    checkpoint_dir : str
        Where checkpoints are saved. e.g. "checkpoints/recon_student".
    interventions : list[str]
        Ordered list of intervention tags to try when plateau is detected.
        These must map to entries in the InterventionExecutor.
    baseline_result : float | None
        Known baseline result before any training, for sanity checking.
    notes : str
        Any additional context, known issues, or hardware requirements.
    extra : dict
        Domain-specific parameters passed to the scaffold generator.
        e.g. {"k_near_max": 5, "k_far_min": 15, "t_max": 70}
    """
    name:                   str
    description:            str
    modality:               str
    data_path:              str
    data_format:            str
    primary_metric:         str
    primary_metric_target:  float
    head:                   str
    loss:                   str
    eval_script:            str
    checkpoint_dir:         str
    interventions:          list[str]
    data_notes:             str       = ""
    teacher:                str | None = None
    baseline_result:        float | None = None
    notes:                  str       = ""
    extra:                  dict      = field(default_factory=dict)

    def validate(self) -> list[str]:
        """Return list of validation errors (empty = OK)."""
        errors = []
        valid_modalities = {"image", "audio", "telemetry", "tabular"}
        valid_formats    = {"hdf5", "wav", "csv", "npy", "folder_of_images", "pt"}
        valid_heads      = {"RoPETemporalHead", "SubspaceAD", "ProjectionHead",
                           "QuasimetricHead", "ClassifierHead", "MLPHead",
                           "IsolationForest"}
        valid_losses     = {"triplet_infonce", "infonce", "distillation",
                           "subspace", "crossentropy", "mse"}

        if self.modality not in valid_modalities:
            errors.append(f"modality '{self.modality}' not in {valid_modalities}")
        if self.data_format not in valid_formats:
            errors.append(f"data_format '{self.data_format}' not in {valid_formats}")
        if self.head not in valid_heads:
            errors.append(f"head '{self.head}' not in {valid_heads}")
        if self.loss not in valid_losses:
            errors.append(f"loss '{self.loss}' not in {valid_losses}")
        if not self.name.replace("_", "").isalnum():
            errors.append(f"name '{self.name}' must be alphanumeric + underscore")
        if not self.interventions:
            errors.append("interventions list must not be empty")
        return errors

    def summary(self) -> str:
        lines = [
            f"Domain: {self.name}",
            f"  Description:  {self.description}",
            f"  Modality:     {self.modality}  ({self.data_format})",
            f"  Data:         {self.data_path}",
            f"  Teacher:      {self.teacher or 'none (train from scratch)'}",
            f"  Head:         {self.head}",
            f"  Loss:         {self.loss}",
            f"  Target:       {self.primary_metric} > {self.primary_metric_target}",
            f"  Checkpoint:   {self.checkpoint_dir}",
            f"  Interventions ({len(self.interventions)}): "
            + ", ".join(self.interventions[:4])
            + ("..." if len(self.interventions) > 4 else ""),
        ]
        if self.notes:
            lines.append(f"  Notes:        {self.notes}")
        return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# Domain registry — all known domains
# ─────────────────────────────────────────────────────────────────────────────

REGISTRY: dict[str, DomainSpec] = {}


def register(spec: DomainSpec) -> DomainSpec:
    errors = spec.validate()
    if errors:
        raise ValueError(f"DomainSpec '{spec.name}' invalid:\n" + "\n".join(errors))
    REGISTRY[spec.name] = spec
    return spec


# ── Existing production domains ───────────────────────────────────────────────

register(DomainSpec(
    name="recon",
    description="Visual quasimetric learning from outdoor Jackal robot trajectories at 4Hz.",
    modality="image",
    data_path=r".\recon_data\recon_release",
    data_format="hdf5",
    data_notes=(
        "images/rgb_left stores JPEG bytes as fixed-length HDF5 strings — "
        "requires PIL/BytesIO decode. jackal/position is [T,3] metres. "
        "T varies (6 to 82), typical T=70."
    ),
    primary_metric="auroc",
    primary_metric_target=0.95,
    teacher=None,
    head="RoPETemporalHead",
    loss="triplet_infonce",
    eval_script="eval_recon_quasimetric.py",
    checkpoint_dir=r"checkpoints\recon_student",
    baseline_result=0.756,
    interventions=[
        "triplet_infonce",       # ✅ done — same-trajectory hard negatives
        "rope_head",             # ✅ done — RoPETemporalHead on frozen encoder
        "increase_k_far",        # push k_far_max 40 → 70 for harder negatives
        "colour_jitter_strong",  # brightness 0.4, contrast 0.4
        "dinov2_distillation",   # distil DINOv2-small → StudentEncoder
        "coordinate_encoder",    # feed (x,y) into encoder as extra channels
        "larger_capacity",       # expand CNN to 3×64→128→256→128
    ],
    notes="Phase 1 AUROC 0.818, Phase 2 AUROC 0.9499 pair mode, 0.8630 held-out.",
    extra={"k_near_max": 5, "k_far_min": 15, "k_far_max": 40, "t_max": 70,
           "latent_dim": 128, "embed_dim": 96},
))

register(DomainSpec(
    name="bearing",
    description="Bearing fault detection from CWRU vibration spectrograms.",
    modality="image",
    data_path=r".\data\cwru",
    data_format="npy",
    primary_metric="auroc",
    primary_metric_target=1.0,
    teacher="dinov2_small",
    head="SubspaceAD",
    loss="distillation",
    eval_script="eval_cwru_bearing.py",
    checkpoint_dir=r"checkpoints\bearing",
    baseline_result=1.0,
    interventions=[
        "subspace_ad_k16",       # ✅ done — AUROC 1.0000
        "subspace_ad_k32",       # try wider subspace
        "patchcore_comparison",  # PatchCore baseline
    ],
    notes="AUROC 1.0000 at k=16. Already at target — maintenance mode.",
    extra={"k": 16},
))

register(DomainSpec(
    name="cardiac",
    description="Cardiac audio anomaly detection from phonocardiogram recordings.",
    modality="audio",
    data_path=r".\data\cardiac",
    data_format="wav",
    primary_metric="auroc",
    primary_metric_target=0.85,
    teacher="beats",
    head="ProjectionHead",
    loss="distillation",
    eval_script="eval_cardiac_audio.py",
    checkpoint_dir=r"checkpoints\cardiac",
    baseline_result=0.889,  # confirmed 2026-03-29, eval on 400 PhysioNet clips, k=32
    interventions=[
        "beats_distillation",    # ✅ done — AUROC 0.889 confirmed (k=32, 0.04ms)
        "longer_training",       # extend from 6 → 20 epochs
        "stronger_augmentation", # pitch shift + time warp
        "wav2vec2_distillation", # try wav2vec2-base teacher
        "m2d_distillation",      # M2D masked audio autoencoder teacher
    ],
    notes="Best checkpoint epoch 4, cos_sim=0.865. Eval pending.",
    extra={"sample_rate": 16000},
))

register(DomainSpec(
    name="smap",
    description="SMAP/MSL satellite telemetry anomaly detection.",
    modality="telemetry",
    data_path=r".\data\smap",
    data_format="npy",
    primary_metric="auroc",
    primary_metric_target=0.85,
    teacher=None,
    head="SubspaceAD",
    loss="subspace",
    eval_script="eval_smap_msl.py",
    checkpoint_dir=r"checkpoints\smap",
    baseline_result=0.7730,
    interventions=[
        "hybrid_pca_drift_k16",      # ✅ done — AUROC 0.7730
        "robust_pca_cleaning",       # remove contaminated training windows — NEXT
        "subspace_ad_k32_cleaned",   # wider subspace after cleaning
        "per_channel_normalisation", # normalise each channel independently
        "longer_windows",            # w 128 → 256
    ],
    notes="AUROC 0.7730 confirmed. Hybrid PCA+drift = 60/81 pass. Contamination diagnosis was wrong — detector mismatch was the bottleneck. Hard channels E-2/E-3/E-4/T-1/T-2 need FFT features. Next: fft_features.",
    extra={"k": 16, "window": 128, "anomaly_fraction_train": 0.18},
))

register(DomainSpec(
    name="mimii",
    description="MIMII industrial machine anomaly detection (fan/pump/slider/valve).",
    modality="audio",
    data_path=r".\data\mimii",
    data_format="wav",
    primary_metric="auroc",
    primary_metric_target=0.95,
    teacher="dinov2_small",
    head="SubspaceAD",
    loss="distillation",
    eval_script="eval_mimii.py",
    checkpoint_dir=r"checkpoints\mimii",
    baseline_result=0.9313,
    interventions=[
        "sigreg_distillation",       # ✅ done — AUROC 0.9313 (4/4 machine types)
        "beats_audio_teacher",       # try BEATs as audio-specific teacher
        "subspace_ad_k32",           # wider subspace for more complex machines
        "per_machine_heads",         # separate head per machine type
    ],
    notes="4/4 machine types above 0.90. Close to target.",
    extra={"machine_types": ["fan", "pump", "slider", "valve"]},
))


register(DomainSpec(
    name="mvtec",
    description="MVTec AD — 15-category industrial anomaly detection benchmark.",
    modality="image",
    data_path=r".\data\mvtec",
    data_format="folder_of_images",
    data_notes=(
        "Standard MVTec layout: {category}/train/good/*.png (normal), "
        "{category}/test/good/*.png (normal test), {category}/test/{defect}/*.png (anomalous). "
        "15 categories: carpet grid leather tile wood bottle cable capsule hazelnut "
        "metal_nut pill screw toothbrush transistor zipper. "
        "Resize to 256x256, center-crop to 224x224. License: CC BY-NC-SA 4.0."
    ),
    primary_metric="auroc",
    primary_metric_target=0.88,
    teacher=None,
    head="SubspaceAD",
    loss="subspace",
    eval_script="eval_mvtec.py",
    checkpoint_dir=r"checkpoints\mvtec",
    baseline_result=0.8152,  # DINOv2 α=0.5 ensemble k=32 — 12 runs 2026-03-30
    interventions=[
        "global_subspace_ad",        # done — 0.685 (k=16 global random)
        "patch_subspace_ad",         # done — 0.745 (k=16 patch random)
        "subspace_k32",              # done — 0.790 (k=32 ensemble, BEST)
        "pretrained_encoder",        # done — 0.752 (RECON k=32)
        "subspace_k64",              # done — 0.776 (k=64, degraded)
        "dinov2_distillation",       # ✅ done — 0.8152 (DINOv2 ensemble k=32, 30 epochs)
        "dinov2_60epoch_spatial",    # ✅ running overnight α=0.2
        "murf_distillation",          # ✅ running — MuRF 30ep scales=[0.5,1.0,1.5] floor=0.0007
        "murf_recon_init",            # NEXT after MuRF eval — RECON init + MuRF + GPS grounding
        "particle_subspace_ad",      # DLP-lite particle encoder (arXiv:2603.04553)
        "augmented_normal_training", # after particle eval
    ],
    notes=(
        "12 runs 2026-03-30. Best: DINOv2 α=0.5 ensemble k=32 = 0.8152 (BEST). "
        "MuRF [0.5,1.0,1.5]=0.796 (0.5× hurts leather 0.797→0.640). "
        "MuRF [0.75,1.0,1.5] + [1.0,1.5] running overnight. "
        "Grounding: DINOv2 cos_sim=0.977, random=0.9965 — defect visibility is ceiling. "
        "Oracle all runs = 0.842. Gap to 0.88 = 0.065pp."
    ),
    extra={
        "k": 32,
        "categories": [
            "carpet","grid","leather","tile","wood",
            "bottle","cable","capsule","hazelnut","metal_nut",
            "pill","screw","toothbrush","transistor","zipper",
        ],
        "image_size": 224,
    },
))

# ── Template for new domains ──────────────────────────────────────────────────

def new_domain_template() -> str:
    """Return a filled-in DomainSpec template string for a new domain."""
    return '''register(DomainSpec(
    name="my_domain",
    description="One sentence describing the task.",
    modality="image",           # "image" | "audio" | "telemetry" | "tabular"
    data_path=r".\\data\\my_domain",
    data_format="hdf5",         # "hdf5" | "wav" | "csv" | "npy" | "folder_of_images"
    data_notes="Describe key layout, gotchas, decode requirements.",
    primary_metric="auroc",
    primary_metric_target=0.90,
    teacher=None,               # None | "dinov2_small" | "beats" | "wav2vec2"
    head="ProjectionHead",      # "RoPETemporalHead" | "SubspaceAD" | "ProjectionHead" | ...
    loss="triplet_infonce",     # "triplet_infonce" | "distillation" | "subspace" | ...
    eval_script="eval_my_domain.py",
    checkpoint_dir=r"checkpoints\\my_domain",
    baseline_result=None,
    interventions=[
        "baseline_run",         # first run, no changes
        "increase_capacity",    # second intervention if plateau
        "stronger_aug",         # third
        "teacher_distillation", # etc.
    ],
    notes="Any extra context.",
    extra={},                   # domain-specific kwargs passed to scaffold
))
'''


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse, sys

    ap = argparse.ArgumentParser(description="CORTEX-PE domain registry")
    ap.add_argument("command", choices=["list", "show", "template", "validate"],
                    help="list: show all domains | show: full spec | "
                         "template: print new domain template | validate: check spec")
    ap.add_argument("--domain", default=None)
    args = ap.parse_args()

    if args.command == "list":
        print(f"\nCORTEX-PE Domain Registry  ({len(REGISTRY)} domains)\n")
        for name, spec in REGISTRY.items():
            status = "✅" if spec.baseline_result and spec.baseline_result >= spec.primary_metric_target else "🔄"
            print(f"  {status}  {name:<12}  {spec.primary_metric}>{spec.primary_metric_target:.2f}  "
                  f"baseline={spec.baseline_result or 'none':<6}  {spec.description[:50]}")
        print()

    elif args.command == "show":
        if not args.domain:
            ap.error("--domain required for show")
        spec = REGISTRY.get(args.domain)
        if not spec:
            print(f"Domain '{args.domain}' not found. Available: {list(REGISTRY)}")
            sys.exit(1)
        print(spec.summary())

    elif args.command == "template":
        print(new_domain_template())

    elif args.command == "validate":
        if args.domain:
            specs = [REGISTRY[args.domain]] if args.domain in REGISTRY else []
        else:
            specs = list(REGISTRY.values())
        all_ok = True
        for spec in specs:
            errors = spec.validate()
            if errors:
                print(f"❌ {spec.name}: {errors}")
                all_ok = False
            else:
                print(f"✅ {spec.name}: OK")
        if all_ok:
            print("\nAll specs valid.")
